PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

#CodeName
EVEREST_CODENAME := Lukla

# Increase EVEREST Version with each major release.
EVEREST_VERSION := 1.5
EVEREST_BUILD_TYPE ?= UNOFFICIAL

# Internal version
LINEAGE_VERSION := EverestOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(EVEREST_VERSION)-$(EVEREST_BUILD_TYPE)

# Display version
LINEAGE_DISPLAY_VERSION := EverestOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(EVEREST_VERSION)
